### ISSUE TITLE
Se me pega cuando Wagemans está cerca

### ISSUE THREAD

**Issue by itcr3442** [JFPenguin/CookTime#16]
En química eso se llamaría una reacción redox, verdad @AleQuesada2012? :v

**Comment by itcr3442** [comment]
Debo agregar que, no, no me salen wagefurros

**Comment by Domtaxx** [comment]
ya estoy cerca, tal vez lo unico que se pegue sean nuestros apasionados corazones <3

**Comment by itcr3442** [comment]
> ya estoy cerca, tal vez lo unico que se pegue sean nuestros apasionados corazones <3

\                       /
  \                    /
    \                 /
      \              /
•      \           /
         \        /
•         \     /
            \  /
             \/

**Comment by itcr3442** [comment]
> ya estoy cerca, tal vez lo unico que se pegue sean nuestros apasionados corazones <3

```\                       /
  \                    /
    \                 /
      \              /
•      \           /
         \        /
•         \     /
            \  /
             \/```

**Comment by JoeA42** [comment]
Chao
